[package]
name = "gun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
bitcoin = {version = "0.29.2", features = ["base64"] }
bitcoincore-rpc = "0.16.0"
clap = { version = "4.1.8", features = ["derive"] }
env_logger = "0.10.0"
hex = "0.4.3"
log = "0.4.17"
regex = "1.7.1"
ripemd = "0.1.3"
serde = { version = "1.0.152", features = ["derive"] }
sha2 = "0.10.6"
toml = "0.7.2"
yansi = "0.5.1"
