[package]
name = "indigo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
bitcoin = {version = "0.29.2", features = ["base64"] }
bitcoincore-rpc = "0.16.0"
clap = { version = "4.1.8", features = ["derive"] }
env_logger = "0.10.0"
futures-util = "0.3.26"
hex = "0.4.3"
log = "0.4.17"
rand = "0.8.5"
regex = "1.7.1"
ripemd = "0.1.3"
secp256k1 = { version = "0.26.0", features = ["rand-std"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.94"
sha2 = "0.10.6"
tokio = { version = "1.26.0", features = ["full"] }
tokio-tungstenite = { version = "0.18.0", features = ["rustls-tls-webpki-roots"] }
toml = "0.7.2"
yansi = "0.5.1"
